// ABI générée depuis backend/artifacts/contracts/Meridian.sol/Meridian.json
export const meridianAbi = [
  { inputs: [{ internalType: "address", name: "owner", type: "address" }], name: "OwnableInvalidOwner", type: "error" },
  { inputs: [{ internalType: "address", name: "account", type: "address" }], name: "OwnableUnauthorizedAccount", type: "error" },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  { inputs: [{ internalType: "address", name: "token", type: "address" }], name: "SafeERC20FailedOperation", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "transactionID", type: "bytes32" },
      { indexed: true, internalType: "address", name: "buyer", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
      { indexed: false, internalType: "enum InternalFunctions.Currency", name: "currency", type: "uint8" },
    ],
    name: "FundsDeposited",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "transactionID", type: "bytes32" },
      { indexed: true, internalType: "address", name: "seller", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
      { indexed: false, internalType: "enum InternalFunctions.Currency", name: "currency", type: "uint8" },
    ],
    name: "FundsWithdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
      { indexed: true, internalType: "address", name: "newOwner", type: "address" },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "transactionID", type: "bytes32" },
      { indexed: true, internalType: "address", name: "buyer", type: "address" },
      { indexed: true, internalType: "address", name: "seller", type: "address" },
    ],
    name: "TransactionAborted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "transactionID", type: "bytes32" },
      { indexed: true, internalType: "address", name: "seller", type: "address" },
    ],
    name: "TransactionCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "transactionID", type: "bytes32" },
      { indexed: true, internalType: "address", name: "buyer", type: "address" },
      { indexed: true, internalType: "address", name: "seller", type: "address" },
    ],
    name: "TransactionDateOverdue",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "transactionID", type: "bytes32" },
      { indexed: false, internalType: "enum InternalFunctions.UserType", name: "userType", type: "uint8" },
      { indexed: true, internalType: "address", name: "userAddress", type: "address" },
    ],
    name: "TransactionDetailsSaved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "transactionID", type: "bytes32" },
      { indexed: true, internalType: "address", name: "buyer", type: "address" },
      { indexed: true, internalType: "address", name: "seller", type: "address" },
    ],
    name: "TransactionFinished",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "transactionID", type: "bytes32" },
      { indexed: true, internalType: "address", name: "buyer", type: "address" },
    ],
    name: "TransactionInitialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "transactionID", type: "bytes32" },
      { indexed: false, internalType: "enum InternalFunctions.UserType", name: "userType", type: "uint8" },
      { indexed: true, internalType: "address", name: "userAddress", type: "address" },
    ],
    name: "TransactionPartiallySigned",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "transactionID", type: "bytes32" },
      { indexed: true, internalType: "address", name: "buyer", type: "address" },
      { indexed: true, internalType: "address", name: "seller", type: "address" },
    ],
    name: "TransactionSigned",
    type: "event",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "_transactionID", type: "bytes32" },
      { internalType: "string", name: "_billNumber", type: "string" },
    ],
    name: "createTransaction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "_transactionID", type: "bytes32" }],
    name: "depositFunds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "_transactionID", type: "bytes32" }],
    name: "getTransaction",
    outputs: [
      {
        components: [
          { internalType: "enum InternalFunctions.WorkflowStatus", name: "workflowStatus", type: "uint8" },
          { internalType: "string", name: "billNumber", type: "string" },
          {
            components: [
              { internalType: "enum InternalFunctions.UserType", name: "userType", type: "uint8" },
              { internalType: "address", name: "userAddress", type: "address" },
              { internalType: "bool", name: "isSubjectedToSanctions", type: "bool" },
            ],
            internalType: "struct InternalFunctions.User",
            name: "buyer",
            type: "tuple",
          },
          {
            components: [
              { internalType: "enum InternalFunctions.UserType", name: "userType", type: "uint8" },
              { internalType: "address", name: "userAddress", type: "address" },
              { internalType: "bool", name: "isSubjectedToSanctions", type: "bool" },
            ],
            internalType: "struct InternalFunctions.User",
            name: "seller",
            type: "tuple",
          },
          { internalType: "enum InternalFunctions.Currency", name: "currency", type: "uint8" },
          { internalType: "enum InternalFunctions.TransactionCondition", name: "transactionCondition", type: "uint8" },
          { internalType: "enum InternalFunctions.TransactionModel", name: "transactionModel", type: "uint8" },
          { internalType: "enum InternalFunctions.AdvancePaymentMode", name: "advancePaymentMode", type: "uint8" },
          { internalType: "uint256", name: "advanceAmount", type: "uint256" },
          { internalType: "uint256", name: "totalAmount", type: "uint256" },
          { internalType: "uint256", name: "transactionCancellingDate", type: "uint256" },
          { internalType: "uint256", name: "sellerDepartureDate", type: "uint256" },
          { internalType: "uint256", name: "sellerArrivalDate", type: "uint256" },
          { internalType: "string", name: "containerReference", type: "string" },
          { internalType: "bool", name: "signedByBuyer", type: "bool" },
          { internalType: "bool", name: "signedBySeller", type: "bool" },
          { internalType: "bytes32", name: "billHash", type: "bytes32" },
          { internalType: "uint256", name: "depositedAmount", type: "uint256" },
          { internalType: "uint256", name: "pendingWithdrawalAmount", type: "uint256" },
          { internalType: "bool", name: "depositCompleted", type: "bool" },
          { internalType: "bool", name: "withdrawalCompleted", type: "bool" },
        ],
        internalType: "struct InternalFunctions.Transaction",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "enum InternalFunctions.Currency", name: "currency", type: "uint8" },
          { internalType: "enum InternalFunctions.TransactionCondition", name: "transactionCondition", type: "uint8" },
          { internalType: "enum InternalFunctions.TransactionModel", name: "transactionModel", type: "uint8" },
          { internalType: "enum InternalFunctions.AdvancePaymentMode", name: "advancePaymentMode", type: "uint8" },
          { internalType: "uint256", name: "advanceAmount", type: "uint256" },
          { internalType: "uint256", name: "totalAmount", type: "uint256" },
          { internalType: "uint256", name: "transactionCancellingDate", type: "uint256" },
        ],
        internalType: "struct InternalFunctions.TransactionDetailsInput",
        name: "_details",
        type: "tuple",
      },
      { internalType: "string", name: "_billNumber", type: "string" },
    ],
    name: "initializeTransaction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [], name: "internalID", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "owner", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "renounceOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
  {
    inputs: [
      { internalType: "bytes32", name: "_transactionID", type: "bytes32" },
      {
        components: [
          { internalType: "enum InternalFunctions.Currency", name: "currency", type: "uint8" },
          { internalType: "enum InternalFunctions.TransactionCondition", name: "transactionCondition", type: "uint8" },
          { internalType: "enum InternalFunctions.TransactionModel", name: "transactionModel", type: "uint8" },
          { internalType: "enum InternalFunctions.AdvancePaymentMode", name: "advancePaymentMode", type: "uint8" },
          { internalType: "uint256", name: "advanceAmount", type: "uint256" },
          { internalType: "uint256", name: "totalAmount", type: "uint256" },
          { internalType: "uint256", name: "transactionCancellingDate", type: "uint256" },
        ],
        internalType: "struct InternalFunctions.TransactionDetailsInput",
        name: "_details",
        type: "tuple",
      },
    ],
    name: "saveTransactionDetailsBuyer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "_transactionID", type: "bytes32" },
      {
        components: [
          { internalType: "uint256", name: "departureDate", type: "uint256" },
          { internalType: "uint256", name: "arrivalDate", type: "uint256" },
          { internalType: "string", name: "containerReference", type: "string" },
        ],
        internalType: "struct InternalFunctions.SellerLogisticsInput",
        name: "_logistics",
        type: "tuple",
      },
      {
        components: [
          { internalType: "enum InternalFunctions.Currency", name: "currency", type: "uint8" },
          { internalType: "enum InternalFunctions.TransactionCondition", name: "transactionCondition", type: "uint8" },
          { internalType: "enum InternalFunctions.TransactionModel", name: "transactionModel", type: "uint8" },
          { internalType: "enum InternalFunctions.AdvancePaymentMode", name: "advancePaymentMode", type: "uint8" },
          { internalType: "uint256", name: "advanceAmount", type: "uint256" },
          { internalType: "uint256", name: "totalAmount", type: "uint256" },
          { internalType: "uint256", name: "transactionCancellingDate", type: "uint256" },
        ],
        internalType: "struct InternalFunctions.TransactionDetailsInput",
        name: "_details",
        type: "tuple",
      },
    ],
    name: "saveTransactionDetailsSeller",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "enum InternalFunctions.Currency", name: "_currency", type: "uint8" },
      { internalType: "address", name: "_tokenAddress", type: "address" },
    ],
    name: "setTokenAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "_transactionID", type: "bytes32" }],
    name: "signTransactionBuyer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "_transactionID", type: "bytes32" }],
    name: "signTransactionSeller",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "enum InternalFunctions.Currency", name: "", type: "uint8" }],
    name: "tokenAddresses",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "_transactionID", type: "bytes32" }],
    name: "withdrawFunds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
